### ISSUE TITLE
Regression in InvalidateTokenController

### ISSUE THREAD

**Issue by neiluJ** [ezsystems/ezplatform-http-cache#128]
Hello guys o/

It looks like there is a small regression introduced by this commit https://github.com/ezsystems/ezplatform-http-cache/commit/d6b6436a77958e29ae1c9878e163b863ecef7f46#diff-d2be57f73af42fde591114a654cb9e98R59 

Varnish being always configured as a Trusted Proxy, I think the check needs a "!" on line https://github.com/ezsystems/ezplatform-http-cache/blob/master/src/Controller/InvalidateTokenController.php#L58 

At the moment it only gets a 401 Unauthorized when trying to fetch the invalidation token, causing Varnish to never purge caches. 

Best regards,
Julien

**Comment by andrerom** [comment]
Indeed, @ViniTou seems like something we need to fix for platform.sh support here.

**Comment by ViniTou** [comment]
@neiluJ 
@andrerom 
I have created PR with quick fix targeting `2.0` here:
https://github.com/ezsystems/ezplatform-http-cache/pull/129

**Comment by neiluJ** [comment]
I was trying the standard 3.0.2 using the suggested varnish5.vcl, so this is also useful without platform.sh :) 

Thank you very much for such a quick response!

**Comment by lserwatka** [comment]
@mnocon could you start QA on this one?

**Comment by ViniTou** [comment]
During QA, We also stumbled across this bug, which also could be related to problem https://github.com/ezsystems/ezplatform/pull/537.
