### ISSUE TITLE
[Api][Admin UI] Responses are not taggued - Admin UI is not purged

### ISSUE THREAD

**Issue by Plopix** [ezsystems/ezplatform-http-cache#20]
I might be wrong but I did look into it seriously.

I think the `xkey` header are not set on the Admin UI / API Request.
I still have the X-Location-Id, I have debugged a little bit, and I ended up here:
https://github.com/ezsystems/ezplatform-http-cache/blob/65cf537126864e32ed389cae9b478a7694a9fdef/src/EventSubscriber/HttpCacheResponseSubscriber.php#L42

`$view` is null.

Then when I publish a new content or a change, the Front is updated accordingly, the purge request is done, but in AdminUI it is not purged.
That is logic as `/api` responses don't have the tags.

I see 2 possible explanations here:
1/ api calls are cached and should not. (but I think they should)
2/ api calls are not correctly tagged and then not correctly purged. (but the code mentioned above makes me think it was not planned to tag them...)

Did someone try with Varnish in front of Admin UI.

Does that make sense?

EDIT: I have also tried to remove `EzSystemsPlatformHttpCacheBundle` from my kernel.
=> Doing that, it works again, I mean I can see the updae in FrontOffice and in AdminUI.
Of course all based on X-Location-Id

ping @andrerom @bdunogier

**Comment by andrerom** [comment]
It worked a bit differently in the original PR I did on kernel, in that case the code all over was refactored to use tags. it was a bc break, so it was moved out, maybe @bdunogier has some input on how other cached responses are supposed to be rewritten now.
 
Bu I guess the following logic should rather be in a response event so it also covers Varnish, and not just Symfony proxy: https://github.com/ezsystems/ezplatform-http-cache/blob/54c859ee47dd1adcd3bc7dcb60a2c81a7c9148fb/src/Proxy/TagAwareStore.php#L76-L78

**Comment by Plopix** [comment]
Should we adapt the VCL to remove the cache on API request or we could do something like an ApIResponseTagguer that would do something similar to the Location|Content view Tagguer? would it be ok for you? the fact that 1.12 is not Varnish compliant by default is a bit sad, I would like to fix that ASAP
Let me know

**Comment by Plopix** [comment]
And I think the PURGE request is not triggered at all.

**Comment by Plopix** [comment]
This issue shows 2 bugs that are individually fixed in #21 #22.

**Comment by Plopix** [comment]
Update here
#22 fix the Purge call

**Comment by andrerom** [comment]
Closing in favor of JIRA issue: https://jira.ez.no/browse/EZP-28183
