### ISSUE TITLE
EzSystems\PlatformHttpCacheBundle\Proxy\TagAwareStore::purgeAllContent() not implemented 

### ISSUE THREAD

**Issue by volkanakb** [ezsystems/ezplatform-http-cache#28]
purgeAllContent method doesn't seem to be implemented.

https://github.com/ezsystems/ezplatform-http-cache/blob/250149c9a29b7e556c05931a503280568227de87/src/Proxy/TagAwareStore.php#L142

**Comment by andrerom** [comment]
@volkanakb can you test to see if #29 fixes your issue, and maybe shed some more light on when this method is actually called, or if this is just reported since you reviewed the code or something ?

**Comment by volkanakb** [comment]
@andrerom the error occurs when you try to clear the whole cache form the legacy backend. Now i got an error at 

https://github.com/ezsystems/ezplatform-http-cache/blob/c39a368a2226d265ef2f76c53d8a81a213ed32bf/src/Proxy/TagAwareStore.php#L169

Error Message: Call to a member function remove() on null
i guess fs is not set
