### ISSUE TITLE
PHP Fatal error after composer update of friendsofsymfony/http-cache to version 1.4.5

### ISSUE THREAD

**Issue by bjko** [ezsystems/ezplatform-http-cache#57]
After doing a composer update of friendsofsymfony/http-cache from version 1.4.4 to version 1.4.5 you get a PHP Fatal error: 
Cannot redeclare class Symfony\Component\HttpFoundation\RequestMatcherInterface in /var/www/htdocs/app/cache/prod/classes.php on line 973

Not sure what they realy changed. Downgrading and limiting to version 1.4.4 will fix this temporary.

**Comment by andrerom** [comment]
Thanks for reporting @bjko , did the error by any chance give any more clues to which class changed?

If we hit this ourselves we'll fix it, alternatively if this is an enterprise install make sure to report to support.ez.no so we can get someone to look into it sooner.

**Comment by bjko** [comment]
I am sorry, we do not have any idea which changes are responsable for this.

Since the ezpublish-kernel requires friendsofsymfony/http-cache-bundle too, you will later or suner hit this issue.

**Comment by andrerom** [comment]
From what I can see the issue is symfony class cache.

So clearing the cache using ‘rm -rf app/cache/*/*’ (symfony 2.x, adapt path for 3.x) might help avoid the error.

Anyone able to confirm?

**Comment by glye** [comment]
@andrerom Yes, with `rm -rf` or `--no-warmup` it works.
We've hit this now with the next 1.7 release. https://jira.ez.no/browse/EZP-29034

**Comment by andrerom** [comment]
Ok, well 1.13 and 2.x is probably not affected then as it does not use class cache.

1.13 disables it on PHP 7: 
https://github.com/ezsystems/ezplatform/blob/1.13/web/app.php#L39-L41
